import Head from 'next/head';
import React from 'react';
import About from '../components/About';
import Navbar from '../components/Navbar';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import Main from './../components/Main';
import Contact from './../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>GERISHON | WEB DEVELOPER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects/>
      <Contact />
    </div>
  );
}
